add API, fix bug
zevk9191/NewsApi pull request #2
Opened 2022-11-21 09:54 UTC by zevk9191

підключив загрузку новин через API

2022-11-27 11:25 UTC, AlexUnion requested changes
Є грубі помилки, які потребують виправлення

2022-11-27 11:25 UTC, AlexUnion commented on script.js
> +    let response = await fetch(`https://api.nytimes.com/svc/topstories/v2/${chapter}.json?api-key=mXG2yTTr2lwpAgGeDbuyqauFKz44AFEL`, options);
можна скоротити запис до `return fetch()`

2022-11-27 11:25 UTC, AlexUnion commented on main.html
>      <h1 class="header__h1"> New York Times</h1>
чому тут пробіл перед **New**?

2022-11-27 11:25 UTC, AlexUnion commented on main.html
>  <div id="floor">
це можна в main положити

2022-11-27 11:25 UTC, AlexUnion commented on script.js
> +function pagination(array) {
зовсім не зрозуміло що має робити ця функція

2022-11-27 11:25 UTC, AlexUnion commented on script.js
> +    arrowNext.addEventListener("click", () => {
тут допущена груба помилка

2022-11-27 11:25 UTC, AlexUnion commented on script.js
> +    arrowPrev.addEventListener("click", () => {
та ж сама помилка

2022-11-27 11:25 UTC, AlexUnion commented on script.js
> +    currentPage.addEventListener("click", () => {
та ж помилка

2022-11-27 11:25 UTC, AlexUnion commented on script.js
> +    return "url(" + backgroundImg + ") 100% / 100% no-repeat border-box border-box";
може повернутись `url(none)`
для чого це зроблено? Чому просто не задавати background?

2022-11-27 11:25 UTC, AlexUnion commented on script.js
> +        createdNews.spanNews.textContent = currentNews.section.split(/\s+/).map(word => word[0].toUpperCase() + word.substring(1)).join(' ');
в тебе є окремо функція **createNews** для створення елементів
чому б в ній не задавати значення?

2022-11-27 11:25 UTC, AlexUnion commented on styles/floor__style.css
> +    padding: 0 1% 0 1%;
padding: 0 1%;

2022-11-27 11:25 UTC, AlexUnion commented on styles/main__style.css
> +    padding-top: 0.9%;
що це за магічне значення **0.9**?
Чому 0.9, чому не 1?

2022-11-28 18:00 UTC, AlexUnion commented on script.js
> +            .then(main)
main?

2022-11-28 18:01 UTC, AlexUnion commented on script.js
> +    return await fetch(`https://api.nytimes.com/svc/topstories/v2/${chapter}.json?api-key=mXG2yTTr2lwpAgGeDbuyqauFKz44AFEL`, options);
async/await можна прибрати

2022-11-28 18:02 UTC, AlexUnion commented on script.js
> +        currentPg--;
що це?

2022-11-28 18:04 UTC, AlexUnion commented on script.js
> +    function pagination(arrayNews, newsInPg) {
pagination?

2022-11-29 04:55 UTC, zevk9191 commented on script.js
> -    let newsPagination = array.results.slice(start, end);
array.results.slice(start, end);

це і є ця помилка?

2022-12-03 14:05 UTC, AlexUnion commented on script.js
> +        start -= 8;
використання start/end є лишнім, можна без окремих змінних зробити

2022-12-03 14:07 UTC, AlexUnion commented on script.js
>              .catch(err => console.log(err));
було б добре не просто в консолі виводити помилку, а показувати користувачеві її

2022-12-07 15:52 UTC, AlexUnion commented
good job

2022-12-07 15:52 UTC, merged